[tool.poetry]
name = "library"
version = "0.1.0"
description = ""
authors = ["Sunil <sunilbaratam@stackbox.xyz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.2"
sqlalchemy = "^2.0.29"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
